name: Build Rust Project for Linux and Windows

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download paths.txt from original repo
        run: wget https://raw.githubusercontent.com/tmplshdw/cloud_config_workaround/refs/heads/main/paths.txt -O paths.txt

      - name: Append extra paths
        run: echo >> paths.txt; cat extrapaths.txt >> paths.txt

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release

      - name: Build debug
        run: cargo build

      - name: Get binary name
        id: get-bin
        run: |
          echo "bin_name=$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[0].targets[] | select(.kind[] == "bin") | .name')" >> $GITHUB_OUTPUT

      - name: Package release binary
        run: |
          mkdir output
          cp "target/release/${{ steps.get-bin.outputs.bin_name }}" output/
          cp paths.txt output/
          tar -czf linux-release-build.tar.gz -C output .

      - name: Package debug binary
        run: |
          mkdir output_debug
          cp "target/debug/${{ steps.get-bin.outputs.bin_name }}" output_debug/
          cp paths.txt output_debug/
          tar -czf linux-debug-build.tar.gz -C output_debug .

      - name: Upload release binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          files: linux-release-build.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload debug binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          files: linux-debug-build.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Download paths.txt from original repo
        run: Invoke-WebRequest https://raw.githubusercontent.com/tmplshdw/cloud_config_workaround/main/paths.txt -OutFile paths.txt
        shell: powershell

      - name: Append extra paths
        run: |
          Add-Content paths.txt "`r`n"
          Get-Content extrapaths.txt | Add-Content paths.txt
        shell: powershell

      - name: Build release
        run: cargo build --release

      - name: Build debug
        run: cargo build

      - name: Get binary name
        id: get-bin
        shell: bash
        run: |
          echo "bin_name=$(cargo metadata --format-version 1 --no-deps | jq -r '.packages[0].targets[] | select(.kind[] == "bin") | .name')" >> $GITHUB_OUTPUT

      - name: Package release binary
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path output_release
          Copy-Item "target/release/${{ steps.get-bin.outputs.bin_name }}.exe" -Destination output_release/
          Copy-Item paths.txt -Destination output_release/
          Compress-Archive -Path output_release/* -DestinationPath windows-release-build.zip

      - name: Package debug binary
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path output_debug
          Copy-Item "target/debug/${{ steps.get-bin.outputs.bin_name }}.exe" -Destination output_debug/
          Copy-Item paths.txt -Destination output_debug/
          Compress-Archive -Path output_debug/* -DestinationPath windows-debug-build.zip

      - name: Upload release binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          files: windows-release-build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload debug binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          files: windows-debug-build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

